name: Build and test
on: [push, workflow_dispatch, repository_dispatch]

permissions: write-all

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      build: ${{ steps.filter.outputs.build }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            build:
              - 'br2-external/**'
  build:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.build == 'true' && !github.event.act }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.buildroot-ccache
          key: ${{ github.ref }}

      - name: build kernel
        run: ./scripts/compile.sh

      - name: send to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: "${{ github.token }}"
          file: images.tar.xz
          asset_name: images.tar.xz
          tag: latest
          overwrite: true

  default-configuration-test:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !failure() }}
    steps:
      - uses: actions/checkout@v3

      - name: get packages
        if: ${{ env.ACT }}
        run: |
         sudo apt update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
         python3-pip telnet iptables iproute2

      - run: git clone https://github.com/antmicro/pyrav4l2.git tests/pyrav4l2

      - name: test
        uses: ./
        with:
          shared-dir: ./tests
          image: https://github.com/${{ github.repository }}/releases/download/latest/images.tar.xz
          renode-run: |
            ping -c 3 172.16.0.1
            wget example.org
            gpiodetect
            sh gpio.sh
            sh i2c.sh
            python test.py
            pip install ./pyrav4l2
            python controls-enumeration.py
          devices: |
            vivid
            gpio 0 16
            i2c 0x1C
